services:

  db:
    build: ./db
    restart: always
    ports: 
      - "5432:5432"
    env_file: .env
  etl:
    build: ./etl
    depends_on:
      - "db"
    volumes:
      - ../data:/app/data 
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "etl.py"]